### ISSUE TITLE
esp32-hal-bt.h: No such file or directory

### ISSUE THREAD

**Issue by thekurtovic** [pioarduino/platform-espressif32#18]
I'm having issues trying to compile NimBLE, but it works fine when I try using platformio/platform-espressif32 6.8.1.
I'm using the following repo https://github.com/h2zero/esp-nimble-cpp.

These are the steps I've taken:
-Extracted esp-nimble-cpp-master.zip to idf components directory
-Start with espidf-arduino-blink project
-Enabled Bluetooth (Menuconfig>Components>Bluetooth)
-Enabled NimBLE only (Menuconfig>Components>Bluetooth>Host)
-Verified ESP-NimBLE-CPP configuration is visible (Menuconfig>Components)

This is the error. I checked the include path and can see ".../.platformio/packages/framework-arduinoespressif32-src-98cb8087edcca5875bec152528484d34/cores/esp32" is there.
`C:/Users/User/.platformio/packages/framework-espidf@src-4f6948c6ced199d051593b27bfeae287/components/esp_nimble/src/NimBLEDevice.cpp:52:12: fatal error: esp32-hal-bt.h: No such file or directory`

Any idea on what I'm missing?

platformio.ini
```
[env]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
framework = arduino, espidf

board_build.embed_txtfiles =
    managed_components/espressif__esp_insights/server_certs/https_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt

[env:esp32-s3]
board = esp32-s3-devkitc-1
```

Blink.cpp
```
#include <Arduino.h>
#include <NimBLEDevice.h>

void setup() {
    Serial.begin(115200);
    NimBLEDevice::init("");
}
void loop() {
    Serial.println("Hello!");
    delay(1000);
}
```

Output
```
Processing esp32-s3 (board: esp32-s3-devkitc-1; platform: https://github.com/pioarduino/platform-espressif32.git#develop; framework: arduino, espidf)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-s3-devkitc-1.html
PLATFORM: Espressif 32 (51.3.3+develop.sha.2ebdc63) > Espressif ESP32-S3-DevKitC-1-N8 (8 MB QD, No PSRAM)
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
DEBUG: Current (esp-builtin) On-board (esp-builtin) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.0.3
 - framework-arduinoespressif32-libs @ 5.1.0+sha.ecdd485305
 - framework-espidf @ 3.50104.0 (5.1.4)
 - tool-cmake @ 3.21.3
 - tool-esptoolpy @ 4.7.5
 - tool-mklittlefs @ 3.2.0
 - tool-ninja @ 1.9.0
 - tool-riscv32-esp-elf-gdb @ 11.2.0+20220823
 - tool-xtensa-esp-elf-gdb @ 11.2.0+20230208
 - toolchain-esp32ulp @ 1.23500.220830 (2.35.0)
 - toolchain-riscv32-esp @ 12.2.0+20230208
 - toolchain-xtensa-esp32s3 @ 12.2.0+20230208
Warning! Arduino framework as an ESP-IDF component doesn't handle the `variant` field! The default `esp32` variant will be used.
Reading CMake configuration...
Warning! Flash memory size mismatch detected. Expected 8MB, found 16MB!
Please select a proper value in your `sdkconfig.defaults` or via the `menuconfig` target!
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 56 compatible libraries
Scanning dependencies...
Dependency Graph
|-- WiFi @ 3.0.3
Building in release mode
Compiling .pio\build\esp32-s3\src\main.cpp.o
Compiling .pio\build\esp32-s3\esp_nimble\src\NimBLEDevice.cpp.o
Compiling .pio\build\esp32-s3\esp_system\debug_stubs.c.o
Compiling .pio\build\esp32-s3\esp_system\task_wdt\task_wdt.c.o
Compiling .pio\build\esp32-s3\esp_system\task_wdt\task_wdt_impl_timergroup.c.o
Compiling .pio\build\esp32-s3\esp_system\port\cpu_start.c.o
Compiling .pio\build\esp32-s3\esp_system\port\panic_handler.c.o
C:/Users/User/.platformio/packages/framework-espidf@src-4f6948c6ced199d051593b27bfeae287/components/esp_nimble/src/NimBLEDevice.cpp:52:12: fatal error: esp32-hal-bt.h: No such file or directory

**********************************************************************
* Looking for esp32-hal-bt.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp32-hal-bt.h"
* Web  > https://registry.platformio.org/search?q=header:esp32-hal-bt.h
*
**********************************************************************

   52 | #  include "esp32-hal-bt.h"
      |            ^~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio\build\esp32-s3\esp_system\port\esp_system_chip.c.o
Compiling .pio\build\esp32-s3\esp_system\port\brownout.c.o
*** [.pio\build\esp32-s3\esp_nimble\src\NimBLEDevice.cpp.o] Error 1
```

**Comment by Jason2866** [comment]
This is not a good idea:
`-Extracted esp-nimble-cpp-master.zip to idf components directory`

This is not a Platform bug or issue! Your setup is "just" wrong!

**Comment by Jason2866** [comment]
@thekurtovic  Changed an example here https://github.com/Jason2866/platform-espressif32/tree/test/examples/espidf-arduino-littlefs

Don't get irritated by the folder name. It uses h2zero NimBLE as component and compiles a BLE scan example.

**Comment by thekurtovic** [comment]
This was how I was doing it on arduino-esp32 v2, and platform 6.8.1.
I thought it would work since pioarduino adds arduino-esp32 v3 support. Shouldn't it work with pioarduino if platform 6.8.1 works?

What is the difference between jason2866/platform-espressif32 and pioarduino/platform-espressif32?
Your example works but now there's no WiFiClientSecure.

**Comment by Jason2866** [comment]
Yes, there are differences. No it will not work with pioarduino since there are incompatible BLE libraries in Arduino. This BLE libs and others, like WifiClientSecure are removed in my fork `jason2866/platform-espressif32`.
To use WifiClientSecure working pioarduino can be choosen and the Arduino framework needs to be replaced with a version where ALL BLE libs are removed.
In short, there is currently no existing fork where NimBLE **and** WifiClientSecure are both possible.

**Comment by Jason2866** [comment]
@thekurtovic  Solved :-). See example https://github.com/pioarduino/platform-espressif32/tree/develop/examples/espidf-arduino-h2zero-BLE_scan

**Comment by thekurtovic** [comment]
I see, I think I understand now.
Thanks for the new example, helps a lot.

Off topic:
I'm wondering where all these other stuff inside managed_components is coming from. Looks like all the espidf-arduino-... examples have them after compiling. Is it possible to exclude the unused ones or is this how IDF 5 with core 3 is supposed to be? I tried to remove them from dependencies.lock but then build fails.
![mc](https://github.com/user-attachments/assets/9887b1f5-5377-465f-ad0c-5b051eb7d425)

**Comment by Jason2866** [comment]
Exactly as you wrote in your Edit. The YML file is responsible for. The IDF component manager scans this file and install the listed parts.
