### ISSUE TITLE
ETH library fails to compile from source (custom_sdkconfig) on IDF 5.5.x — beginSPI/begin spi_host type mismatch (spi_host_device_t vs int)

### ISSUE THREAD

**Issue by thehellmaker** [pioarduino/platform-espressif32#504]
### Summary

When `custom_sdkconfig` triggers a **from-source** rebuild of the Arduino framework, `libraries/Ethernet/src/ETH.cpp` fails to compile on **ESP-IDF v5.5.4 / arduino-esp32 3.x** with `no declaration matches` for `ETHClass::beginSPI` and `ETHClass::begin`. The `spi_host` parameter type **diverges between source and header**:

- `ETH.cpp` defines it as **`spi_host_device_t`**
- `ETH.h` declares it as **`int`**

Stock builds (prebuilt framework libs) are unaffected because `ETH.cpp` is not recompiled. The failure appears the moment any `custom_sdkconfig` option is set (which forces a from-source build).

### Environment

- Platform: `pioarduino` `platform-espressif32` stable zip (`espressif32 @ 55.3.39`)
- Framework: `framework-arduinoespressif32` 3.x, **ESP-IDF v5.5.4**
- Board: `esp32dev` (ESP32-WROOM)
- Host: macOS, PlatformIO (venv)

### Minimal reproduction

```ini
[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
custom_sdkconfig =
    CONFIG_COMPILER_OPTIMIZATION_SIZE=y
```
`pio run` → fails compiling `ETH.cpp`.

### Errors

```
ETH.cpp:578:6: error: no declaration matches 'bool ETHClass::beginSPI(eth_phy_type_t, int32_t, uint8_t*, int, int, int, SPIClass*, int, int, int, spi_host_device_t, uint8_t)'
ETH.h:284:8: note: candidate is:               'bool ETHClass::beginSPI(eth_phy_type_t, int32_t, uint8_t*, int, int, int, SPIClass*, int, int, int, int, uint8_t)'
ETH.cpp:960:6: error: no declaration matches 'bool ETHClass::begin(eth_phy_type_t, int32_t, int, int, int, spi_host_device_t, int, int, int, uint8_t)'
```
(Earlier, with SPI-Ethernet disabled, the first error is instead `'spi_host_device_t' has not been declared` at `ETH.h:184`.)

### Things tried that do NOT fix it on this version

- `CONFIG_ETH_USE_SPI_ETHERNET=y` (+ W5500/DM9051/KSZ8851SNL) — the commonly cited fix; changes the error from "not declared" to "no declaration matches" but does not resolve it.
- `CONFIG_ETH_ENABLED=n` — **not honored**; `ETH.cpp` (guarded by `#if CONFIG_ETH_ENABLED`) still compiles, so the override isn't reaching the generated `sdkconfig.h` for the Arduino library build.
- `lib_ignore = Ethernet` — framework still compiles its bundled `ETH.cpp`.

### Suggested fixes

1. Align the `beginSPI`/`begin` `spi_host` parameter type between `ETH.h` and `ETH.cpp` (both `spi_host_device_t`) for IDF ≥ 5.5, and/or `#include "driver/spi_master.h"` in `ETH.h` so the type is always declared.
2. Honor `CONFIG_ETH_ENABLED=n` for from-source builds so projects that don't use Ethernet can exclude the library.

Related: espressif/arduino-esp32#11810.

**Comment by thehellmaker** [comment]
Root-caused: `ETH.h` uses `spi_host_device_t` in its public `begin()`/`beginSPI()` signatures but doesn't include `driver/spi_master.h`, and `ETH.cpp` includes `ETH.h` before that header — so from-source (custom_sdkconfig) builds fail. Upstream fix PR: espressif/arduino-esp32#12708 (one-line include-what-you-use). Verified: with the fix a from-source `custom_sdkconfig` build of esp32dev compiles ETH and links cleanly.

**Comment by Jason2866** [comment]
pioarduino does use original releases from espressif for Arduino and IDF. This issue is not caused by pioarduino and can not be solved in pioarduino.
Are you sure using latest Arduino core. When using "stable" it does NOT update to a newer release!
